#Salary Prediction

## Notebook 1: Data Exploration

### Objective

The objective of this notebook is to understand the salary dataset before performing any preprocessing or model training.

In this notebook, we will:

- Import the required libraries.
- Load the dataset.
- Explore the structure of the dataset.
- Check for missing values.
- Check for duplicate records.
- Understand the features.
- Analyze numerical and categorical variables.
- Identify the target variable.
- Make observations that will help in the preprocessing stage.

> **Note:** No preprocessing or model training will be performed in this notebook.

### step 1: import required libraries 
the import library that required for data handeling and analysis

In [ ]:

import pandas as pd
import numpy as np

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

### Step 2: Load Dataset

The original salary dataset is stored inside the **data/raw_data** directory.

After loading the dataset, we verify that it has been imported correctly before beginning our analysis.

In [2]:
df = pd.read_csv(r"D:/machine learning/machine_learning/linear_regression_project/salary_prediction/data/raw_data/salaries.csv")

print("Dataset loaded successfully.")

Dataset loaded successfully.

### Step 3: Initial Data Overview

The first step in understanding any dataset is to inspect its overall structure.

We will examine:

- Dataset Shape
- Dataset Information
- Statistical Summary
- First Five Rows
- Last Five Rows

This helps us understand the available features, their data types, and the overall quality of the dataset.

In [3]:
print(f"Dataset Shape : {df.shape}")
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Dataset Shape : (151445, 11)
Rows    : 151445
Columns : 11

In [4]:
print("Dataset Information\n")

df.info()

Dataset Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151445 entries, 0 to 151444
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           151445 non-null  int64
 1   experience_level    151445 non-null  object
 2   employment_type     151445 non-null  object
 3   job_title           151445 non-null  object
 4   salary              151445 non-null  int64
 5   salary_currency     151445 non-null  object
 6   salary_in_usd       151445 non-null  int64
 7   employee_residence  151445 non-null  object
 8   remote_ratio        151445 non-null  int64
 9   company_location    151445 non-null  object
 10  company_size        151445 non-null  object
dtypes: int64(4), object(7)
memory usage: 12.7+ MB

In [5]:
print("Statistical Summary\n")

df.describe().T

Statistical Summary

,count,mean,std,min,25%,50%,75%,max
work_year,151445.0,2024.435313,0.671842,2020.0,2024.0,2025.0,2025.0,2025.0
salary,151445.0,162837.963135,208012.396413,14000.0,106000.0,147000.0,199000.0,30400000.0
salary_in_usd,151445.0,157527.458411,74150.772377,15000.0,105800.0,146100.0,198000.0,800000.0
remote_ratio,151445.0,20.938625,40.620393,0.0,0.0,0.0,0.0,100.0

In [6]:
print("First Five Rows\n")

df.head()

First Five Rows

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M

In [7]:
print("Last Five Rows\n")

df.tail()

Last Five Rows

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
151440,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
151441,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
151442,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
151443,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
151444,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

### Observations from Initial Data Overview

From the initial exploration, we can observe the following:

- The dataset contains employee salary information collected from different companies and countries.
- The dataset includes both numerical and categorical features.
- The target variable for this project will be **salary_in_usd**.
- Features such as **experience_level**, **employment_type**, **job_title**, and **company_size** are categorical.
- Features such as **remote_ratio** and **work_year** are numerical.
- Further investigation is required to identify missing values and duplicate records before model training.